### ISSUE TITLE
Nič se ne dogaja

### ISSUE THREAD

**Issue by matijapretnar** [nezahabjan/Projekt_MZR#1]
Ker bodo v kratkem kratke predstavitve, čimprej začnite z delom na projektu. Na spletni učilnici sem [objavil navodila](https://ucilnica.fmf.uni-lj.si/mod/forum/discuss.php?d=15136), kako začeti.

**Comment by matijapretnar** [comment]
Ok, zdaj se je začelo dogajati.

**Comment by matijapretnar** [comment]
Čeprav vidim, da mejniki še vedno niso postavljeni :)

**Comment by nezahabjan** [comment]
Sem dodala še mejnike, hvala :)
