### ISSUE TITLE
Odvečne datoteke

### ISSUE THREAD

**Issue by matijapretnar** [nezahabjan/Projekt_MZR#2]
Datoteka `staro.R` verjetno ne spada v repozitorij? Zagotovo pa v repozitorij ne spadajo `.Rhistory` datoteke. Odstranite jih iz repozitorija in jih dodajte v `.gitignore`.

**Comment by nezahabjan** [comment]
Najlepša hvala za opozorilo, bom prečistila in pustila samo uporabno.

Lp, Neža
