### ISSUE TITLE
Premajhno okno

### ISSUE THREAD

**Issue by matijapretnar** [nezahabjan/Projekt_MZR#3]
Pri meni se okno odpre takole, z vsebino samo na zgornji polovici:

<img width="1022" alt="Screenshot 2020-04-02 at 12 09 16" src="https://user-images.githubusercontent.com/1502128/78236788-c846d800-74da-11ea-8e3f-e385b97e1153.png">

A je pri vas enako?

**Comment by nezahabjan** [comment]
Da, enako.. sem že študirala kako to popraviti, pa nisem našla rešitve.

**Comment by nezahabjan** [comment]
Pozdravljeni, sedaj se mi okno odpira v normalni velikosti, upam da tudi pri vas?

Lp, Neža

**Comment by matijapretnar** [comment]
Ja, zdaj dela!
