### ISSUE TITLE
naenkrat ne delujoča aplikacija..

### ISSUE THREAD

**Issue by nezahabjan** [nezahabjan/Projekt_MZR#4]
Pozdravljeni,

imam problem pri delovanju shiny aplikacije, pred dvema dnevoma mi je vse delovalo normalno, server in ui sta bila povezana in conditionalPanel-i so se v redu prikazovali, sedaj pa kar naenkrat ne več.. Nevem kaj bi se lahko takega vmes spremenilo, razmišljala sem tudi o težavi s kakšnim novim paketom. Vem, da aplikacija tudi sicer še nebi delovala pravilno, ampak rada bi vsaj, da sta server in ui usklajena, da lahko popravljam in nadaljujem z ostalimi stvarmi..

Prosila bi vas, če imate kakšen nasvet in mi lahko pomagate?

@matijapretnar

Najlepša hvala že vnaprej,

Lp, Neža

**Comment by nezahabjan** [comment]
Sem že uspela popraviti, hvala vseeno :)

Lep dan, Neža

**Comment by matijapretnar** [comment]
Me veseli!
