### ISSUE TITLE
Nasveti za dokončanje projekta

### ISSUE THREAD

**Issue by nezahabjan** [nezahabjan/Projekt_MZR#5]
Pozdravljeni,

v svoj projekt sem vključila stalen prikaz grafa, na katerem uporabnik dela, tako kot ste mi svetovali na kratki predstavitvi. Prav tako sem odstranila del z ugašanjem luči, ki po tematiki ni spadal zraven, vse probleme razen problema potujočega trgovca pa sem združila na eno stran, ker prikazujejo bolj lastnosti grafov, kot pa dejansko reševanje problemov na njih. 

Prosila bi vas za kakšen komentar/pripombo/predlog, kaj še lahko spremenim, da bo projekt zaključen :)

@matijapretnar
Najlepša hvala že vnaprej,
lepo pozdrav, Neža

**Comment by matijapretnar** [comment]
Pozdravljeni, nekaj komentarjev:
- `libraries/lib.r` verjetno ni več potreben?
- paketov `RGBL` in `eulerian` mi noče naložiti, ker nista več podprta na aktualni verziji R-ja. Kaj lahko storim? V najslabšem primeru v README povejte, katera verzija R-ja je podprta.
- v nalogi je še nekaj slovničnih napak, manjkajoči šumniki, …

**Comment by nezahabjan** [comment]
Najlepša hvala, sem odstranila datoteko libraries in popravila slovnične napake v aplikaciji. Glede obeh paketov pa sem iskala rešitve, za RGBL lahko poskusite z ukazoma
install.packages("BiocManager")
BiocManager::install("RBGL")
BiocManager verzija 3.8 je podprta na verziji 3.5 R studia. Pri meni je to po posodobitvi R studia delovalo v redu. Glede eulerian pa sem poskusila s predhodno nastavitvijo PairViz paketa, eulerian naj bi po novem izhajala iz njega. Upam da bo delovalo, sicer pa bom še popravila.

Najlepša hvala, lp, Neža

**Comment by matijapretnar** [comment]
Ja, zdaj dela. Verjetno bi bilo dobro navodilo za RGBL dodati tudi v README.md. Zdaj ob zagonu dobim napaki:
```
Error in source("server_1.R") : 
  invalid multibyte character in parser at line 30
```
in
```
Error in source("ui_1.R") : 
  invalid multibyte character in parser at line 12
```
Težava je v tem, ker sta omenjeni datoteki v kodni tabeli CP1250 namesto UTF-8.

**Comment by nezahabjan** [comment]
Sem popravila in dodala dodatna navodila v readme.
