### ISSUE TITLE
Računanje ciklov

### ISSUE THREAD

**Issue by matijapretnar** [nezahabjan/Projekt_MZR#7]
Računanje ciklov ne deluje pravilno:
<img width="541" alt="Screenshot 2020-05-26 at 14 21 08" src="https://user-images.githubusercontent.com/1502128/82900126-59c34b00-9f5c-11ea-996a-c0c1f6e4ff7f.png">

**Comment by nezahabjan** [comment]
Pozdravljeni, funkcijo za iskanje ciklov sem sedaj popravila.
Lp, Neža
